import type { BetaRawContentBlockStartEvent, BetaRawContentBlockStopEvent } from "@anthropic-ai/sdk/resources/beta.js";
import type { BetaRawContentBlockDeltaEvent } from "@anthropic-ai/sdk/resources/beta.mjs";

export interface ToolCall {
  /** Arguments passed to the tool function */
  args: Record<string, any>;
  /** Optional result returned by the tool execution */
  result?: any;
}

/**
 * Represents the result of a streaming operation.
 * 
 * Contains the final content generated and information about tools used
 * during the streaming process.
 * 
 * @example
 * ```typescript
 * const result: StreamResult = {
 *   content: "The weather is sunny with a temperature of 72°F.",
 *   usedTools: ["weather_api"],
 *   toolCalls: {
 *     weather_api: [{ args: { location: "NYC" }, result: { temp: 72 } }]
 *   }
 * };
 * ```
 */
export interface StreamResult {
  /** The final content generated by the AI model */
  content: string;
  /** Array of tool names that were used during generation */
  usedTools: string[];
  /** Record of tool calls organized by tool name */
  toolCalls: Record<string, ToolCall[]>;
}

/**
 * Represents a complete agent response with metadata.
 *
 * This interface provides a comprehensive view of an AI agent's response,
 * including the model used, content generated, tools utilized, and metadata.
 *
 * @example
 * ```typescript
 * const response: AgentResponse = {
 *   model: "claude-3-sonnet",
 *   content: "Based on the weather data, it's a beautiful day!",
 *   usedTools: ["weather_api", "calendar_api"],
 *   toolCalls: {},
 *   metadata: {
 *     timestamp: Date.now(),
 *     duration: 1500,
 *     tokensUsed: 250
 *   }
 * };
 * ```
 */
export interface AgentResponse {
  /** The AI model that generated the response */
  model: string;
  /** The response content generated by the model */
  content: string;
  /** Array of tool names used during response generation */
  usedTools: string[];
  /** Record of tool calls made during response generation */
  toolCalls: Record<string, ToolCall[]>;
  /** Optional metadata about the response */
  metadata?: {
    /** Timestamp when the response was generated */
    timestamp: number;
    /** Duration of the response generation in milliseconds */
    duration?: number;
    /** Number of tokens used in the response */
    tokensUsed?: number;
    /** Additional metadata properties */
    [key: string]: any;
  };
}

/**
 * Represents the result of executing multiple agents.
 *
 * This interface aggregates responses from multiple AI agents and provides
 * summary statistics about the execution.
 *
 * @example
 * ```typescript
 * const executionResult: AgentsExecutionResult = {
 *   responses: {
 *     "agent1": {},
 *     "agent2": {}
 *   },
 *   summary: {
 *     totalModels: 2,
 *     successfulExecutions: 2,
 *     failedExecutions: 0,
 *     commonTools: ["weather_api"],
 *     executionTime: 3000
 *   }
 * };
 * ```
 */
export interface AgentsExecutionResult {
  /** Record of responses from different agents, keyed by agent identifier */
  responses: Record<string, AgentResponse>;
  /** Summary statistics of the multi-agent execution */
  summary: {
    /** Total number of models/agents involved */
    totalModels: number;
    /** Number of successful agent executions */
    successfulExecutions: number;
    /** Number of failed agent executions */
    failedExecutions: number;
    /** Array of tools used by multiple agents */
    commonTools: string[];
    /** Total execution time in milliseconds */
    executionTime: number;
  };
}

/**
 * Typed tool call with generic arguments and result types.
 *
 * This interface provides type safety for tool calls by allowing specification
 * of argument and result types through generics.
 *
 * @template TArgs - Type of the tool arguments
 * @template TResult - Type of the tool result
 *
 * @example
 * ```typescript
 * interface WeatherArgs {
 *   location: string;
 *   units: "celsius" | "fahrenheit";
 * }
 *
 * interface WeatherResult {
 *   temperature: number;
 *   condition: string;
 * }
 *
 * const typedCall: TypedToolCall<WeatherArgs, WeatherResult> = {
 *   args: { location: "NYC", units: "fahrenheit" },
 *   result: { temperature: 72, condition: "sunny" },
 *   timestamp: Date.now(),
 *   duration: 150
 * };
 * ```
 */
export interface TypedToolCall<TArgs = Record<string, any>, TResult = any> {
  /** Typed arguments for the tool function */
  args: TArgs;
  /** Optional typed result from the tool execution */
  result?: TResult;
  /** Timestamp when the tool call was made */
  timestamp: number;
  /** Duration of the tool call in milliseconds */
  duration?: number;
}

/**
 * Statistics for tool call usage.
 *
 * This interface tracks usage patterns and performance metrics for tools
 * used by AI agents.
 *
 * @example
 * ```typescript
 * const stats: ToolCallStats = {
 *   toolName: "weather_api",
 *   callCount: 15,
 *   totalDuration: 2500,
 *   averageDuration: 167,
 *   lastCalled: Date.now()
 * };
 * ```
 */
export interface ToolCallStats {
  /** Name of the tool being tracked */
  toolName: string;
  /** Number of times the tool has been called */
  callCount: number;
  /** Total time spent in tool calls in milliseconds */
  totalDuration?: number;
  /** Average duration per tool call in milliseconds */
  averageDuration?: number;
  /** Timestamp of the last tool call */
  lastCalled?: number;
}

/**
 * Union type of all possible normalized chunk types.
 *
 * Defines the different types of streaming chunks that can be processed
 * from AI providers.
 *
 * - `text_delta`: Incremental text content updates
 * - `tool_call_start`: Beginning of a tool call
 * - `tool_call_done`: Completion of a tool call
 * - `tool_result`: Result from a tool execution
 * - `message_start`: Beginning of a message
 * - `message_done`: Completion of a message
 * - `thinking_delta`: Incremental thinking/reasoning updates
 * - `error`: Error information
 *
 * @example
 * ```typescript
 * const chunkType: NormalizedChunkType = "text_delta";
 * ```
 */
export type NormalizedChunkType =
  | "text_delta"
  | "tool_call_start"
  | "tool_call_done"
  | "tool_result"
  | "message_start"
  | "message_done"
  | "thinking_delta"
  | "error";

/**
 * Represents a normalized chunk of streaming data from AI providers.
 *
 * This interface provides a unified format for handling chunks from different
 * AI providers (Anthropic, OpenAI) by normalizing their specific formats
 * into a common structure.
 *
 * @example
 * ```typescript
 * const chunk: NormalizedChunk = {
 *   type: "text_delta",
 *   provider: "anthropic",
 *   timestamp: Date.now(),
 *   data: { text: "Hello, world!" },
 *   originalChunk: {}
 * };
 * ```
 */
export interface NormalizedChunk {
  /** The type of chunk being processed */
  type: NormalizedChunkType;
  /** The AI provider that generated this chunk */
  provider: "anthropic" | "openai";
  /** Timestamp when the chunk was received */
  timestamp: number;
  /** The normalized data payload for this chunk */
  data: {
    /** Text content for text-related chunks */
    text?: string;
    /** Name of the tool for tool-related chunks */
    toolName?: string;
    /** Arguments for tool calls */
    toolArgs?: Record<string, any>;
    /** Result from tool execution */
    toolResult?: any;
    /** Error message for error chunks */
    error?: string;
    /** Additional data properties */
    [key: string]: any;
  };
  /** The original provider-specific chunk data */
  originalChunk?: any;
}

/**
 * Generic callback function for handling any normalized chunk.
 *
 * This type defines a callback that can process any type of normalized chunk.
 * The callback can be synchronous or asynchronous.
 *
 * @param chunk - The normalized chunk to process
 * @returns Promise<void> | void
 *
 * @example
 * ```typescript
 * const callback: ChunkCallback = async (chunk) => {
 *   console.log(`Processing ${chunk.type} chunk from ${chunk.provider}`);
 *   // Process the chunk...
 * };
 * ```
 */
export type ChunkCallback = (chunk: NormalizedChunk) => void | Promise<void>;

/**
 * Callback function for handling specific chunk types.
 *
 * This type defines a callback that processes the data payload from a specific
 * chunk type. The callback can be synchronous or asynchronous.
 *
 * @param data - The data payload from the chunk
 * @returns Promise<void> | void
 *
 * @example
 * ```typescript
 * const textCallback: ChunkTypeCallback = async (data) => {
 *   if (data.text) {
 *     console.log("Received text:", data.text);
 *   }
 * };
 * ```
 */
export type ChunkTypeCallback = (data: NormalizedChunk["data"]) => void | Promise<void>;

/**
 * Configuration object for chunk handlers.
 *
 * This interface defines all the callback functions that can be registered
 * to handle different types of chunks during processing. All callbacks are
 * optional and can be async.
 *
 * @example
 * ```typescript
 * const handlers: ChunkHandlerConfig = {
 *   onTextDelta: (data) => console.log("Text:", data.text),
 *   onToolCallStart: (data) => console.log("Tool started:", data.toolName),
 *   onToolCallDone: (data) => console.log("Tool finished:", data.toolName),
 *   onError: (data) => console.error("Error:", data.error),
 *   onAnyChunk: (chunk) => console.log("Any chunk:", chunk.type),
 *   anthropic: {
 *     onContentBlockDelta: (chunk) => console.log("Anthropic delta:", chunk)
 *   },
 *   openai: {
 *     onResponseOutputItemAdded: (chunk) => console.log("OpenAI item added:", chunk)
 *   }
 * };
 * ```
 */
export interface ChunkHandlerConfig {
  /** Callback for text delta chunks */
  onTextDelta?: ChunkTypeCallback;
  /** Callback for tool call start chunks */
  onToolCallStart?: ChunkTypeCallback;
  /** Callback for tool call done chunks */
  onToolCallDone?: ChunkTypeCallback;
  /** Callback for tool result chunks */
  onToolResult?: ChunkTypeCallback;
  /** Callback for message start chunks */
  onMessageStart?: ChunkTypeCallback;
  /** Callback for message done chunks */
  onMessageDone?: ChunkTypeCallback;
  /** Callback for thinking delta chunks */
  onThinkingDelta?: ChunkTypeCallback;
  /** Callback for error chunks */
  onError?: ChunkTypeCallback;
  /** Callback for any chunk type */
  onAnyChunk?: ChunkCallback;

  /** Provider-specific handlers for Anthropic */
  anthropic?: {
    /** Handler for Anthropic content block delta chunks */
    onContentBlockDelta?: (chunk: BetaRawContentBlockDeltaEvent) => void | Promise<void>;
    /** Handler for Anthropic content block start chunks */
    onContentBlockStart?: (chunk: BetaRawContentBlockStartEvent) => void | Promise<void>;
    /** Handler for Anthropic content block stop chunks */
    onContentBlockStop?: (chunk: BetaRawContentBlockStopEvent) => void | Promise<void>;
  };
  /** Provider-specific handlers for OpenAI */
  openai?: {
    /** Handler for OpenAI response output item added chunks */
    onResponseOutputItemAdded?: (chunk: any) => void | Promise<void>;
    /** Handler for OpenAI response output item done chunks */
    onResponseOutputItemDone?: (chunk: any) => void | Promise<void>;
  };
}
